forge "http://forge.puppetlabs.com"

mod 'puppetlabs/sqlite3',
    :git => "git://github.com/puppetlabs/puppetlabs-sqlite.git"

mod 'stahnma/epel',
    :git => "git://github.com/stahnma/puppet-module-epel.git"

mod 'puppetlabs/stdlib',
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod 'jfryman/nginx',
    :git => "git://github.com/jfryman/puppet-nginx.git"

mod 'puppetlabs/ntp',
    :git => "git://github.com/puppetlabs/puppetlabs-ntp.git"

mod 'ripienaar/concat',
    :git => "git://github.com/ripienaar/puppet-concat.git"

mod 'puppetlabs/mysql',
    :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"

mod 'thias/sysctl',
    :git => "https://github.com/thias/puppet-sysctl"

mod 'saz/sudo',
    :git => "git@github.com:saz/puppet-sudo.git"

mod 'maestrodev/rvm',
    :git => 'https://github.com/maestrodev/puppet-rvm.git',
    :ref => 'maestrodev'

mod 'puppetlabs/firewall',
    :git => 'https://github.com/puppetlabs/puppetlabs-firewall'

mod 'puppetlabs/postgresql',
    :git => 'https://github.com/puppetlabs/puppetlabs-postgresql'

mod 'saz/memcached',
    :git => 'https://github.com/saz/puppet-memcached'

mod 'camptocamp/augeas',
    :git => 'https://github.com/camptocamp/puppet-augeas'


