forge "http://forge.puppetlabs.com"

mod 'sqlite3',
    :git => "git://github.com/puppetlabs/puppetlabs-sqlite3.git"

mod 'stdlib',
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod 'apt',
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod 'nginx',
    :git => "git://github.com/jfryman/puppet-nginx.git"

mod 'ntp',
    :git => "git://github.com/puppetlabs/puppetlabs-ntp.git"

mod 'concat',
    :git => "git://github.com/ripienaar/puppet-concat.git"

mod 'postgresql',
    :git => 'git://github.com/akumria/puppet-postgresql.git'

mod 'monit',
    :git => 'git://github.com/salimane/puppet-monit.git'

mod 'rbenv',
    :git => 'git://github.com/alup/puppet-rbenv.git'

mod 'memcached',
    :git => 'git://github.com/saz/puppet-memcached.git'

